Search.appendIndex(
    [
                {
            "fqsen": "\\PdoGsb",
            "name": "PdoGsb",
            "summary": "Classe\u0020d\u0027acc\u00E8s\u0020aux\u0020donn\u00E9es.",
            "url": "classes/PdoGsb.html"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020priv\u00E9,\u0020cr\u00E9e\u0020l\u0027instance\u0020de\u0020PDO\u0020qui\u0020sera\u0020sollicit\u00E9e\npour\u0020toutes\u0020les\u0020m\u00E9thodes\u0020de\u0020la\u0020classe",
            "url": "classes/PdoGsb.html#method___construct"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "M\u00E9thode\u0020destructeur\u0020appel\u00E9e\u0020d\u00E8s\u0020qu\u0027il\u0020n\u0027y\u0020a\u0020plus\u0020de\u0020r\u00E9f\u00E9rence\u0020sur\u0020un\nobjet\u0020donn\u00E9,\u0020ou\u0020dans\u0020n\u0027importe\u0020quel\u0020ordre\u0020pendant\u0020la\u0020s\u00E9quence\u0020d\u0027arr\u00EAt.",
            "url": "classes/PdoGsb.html#method___destruct"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetPdoGsb\u0028\u0029",
            "name": "getPdoGsb",
            "summary": "Fonction\u0020statique\u0020qui\u0020cr\u00E9e\u0020l\u0027unique\u0020instance\u0020de\u0020la\u0020classe\nAppel\u0020\u003A\u0020\u0024instancePdoGsb\u0020\u003D\u0020PdoGsb\u003A\u003AgetPdoGsb\u0028\u0029\u003B",
            "url": "classes/PdoGsb.html#method_getPdoGsb"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetInfosVisiteur\u0028\u0029",
            "name": "getInfosVisiteur",
            "summary": "Retourne\u0020les\u0020informations\u0020d\u0027un\u0020visiteur",
            "url": "classes/PdoGsb.html#method_getInfosVisiteur"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetMdpVisiteur\u0028\u0029",
            "name": "getMdpVisiteur",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getMdpVisiteur"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetCodeVisiteur\u0028\u0029",
            "name": "getCodeVisiteur",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getCodeVisiteur"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetInfosComptable\u0028\u0029",
            "name": "getInfosComptable",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getInfosComptable"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetMdpComptable\u0028\u0029",
            "name": "getMdpComptable",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getMdpComptable"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetCodeComptable\u0028\u0029",
            "name": "getCodeComptable",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getCodeComptable"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AsetCodeA2f\u0028\u0029",
            "name": "setCodeA2f",
            "summary": "",
            "url": "classes/PdoGsb.html#method_setCodeA2f"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AsetCodeA2fComptable\u0028\u0029",
            "name": "setCodeA2fComptable",
            "summary": "",
            "url": "classes/PdoGsb.html#method_setCodeA2fComptable"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetLesFraisHorsForfait\u0028\u0029",
            "name": "getLesFraisHorsForfait",
            "summary": "Retourne\u0020sous\u0020forme\u0020d\u0027un\u0020tableau\u0020associatif\u0020toutes\u0020les\u0020lignes\u0020de\u0020frais\nhors\u0020forfait\u0020concern\u00E9es\u0020par\u0020les\u0020deux\u0020arguments.",
            "url": "classes/PdoGsb.html#method_getLesFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetNbjustificatifs\u0028\u0029",
            "name": "getNbjustificatifs",
            "summary": "Retourne\u0020le\u0020nombre\u0020de\u0020justificatif\u0020d\u0027un\u0020visiteur\u0020pour\u0020un\u0020mois\u0020donn\u00E9",
            "url": "classes/PdoGsb.html#method_getNbjustificatifs"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetLesFraisForfait\u0028\u0029",
            "name": "getLesFraisForfait",
            "summary": "Retourne\u0020sous\u0020forme\u0020d\u0027un\u0020tableau\u0020associatif\u0020toutes\u0020les\u0020lignes\u0020de\u0020frais\nau\u0020forfait\u0020concern\u00E9es\u0020par\u0020les\u0020deux\u0020arguments",
            "url": "classes/PdoGsb.html#method_getLesFraisForfait"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetLesIdFrais\u0028\u0029",
            "name": "getLesIdFrais",
            "summary": "Retourne\u0020tous\u0020les\u0020id\u0020de\u0020la\u0020table\u0020FraisForfait",
            "url": "classes/PdoGsb.html#method_getLesIdFrais"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AmajFraisForfait\u0028\u0029",
            "name": "majFraisForfait",
            "summary": "Met\u0020\u00E0\u0020jour\u0020la\u0020table\u0020ligneFraisForfait\nMet\u0020\u00E0\u0020jour\u0020la\u0020table\u0020ligneFraisForfait\u0020pour\u0020un\u0020visiteur\u0020et\nun\u0020mois\u0020donn\u00E9\u0020en\u0020enregistrant\u0020les\u0020nouveaux\u0020montants",
            "url": "classes/PdoGsb.html#method_majFraisForfait"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AmajFraisHorsForfait\u0028\u0029",
            "name": "majFraisHorsForfait",
            "summary": "",
            "url": "classes/PdoGsb.html#method_majFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003ArefuserFraisHorsForfait\u0028\u0029",
            "name": "refuserFraisHorsForfait",
            "summary": "",
            "url": "classes/PdoGsb.html#method_refuserFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetMoisSuivant\u0028\u0029",
            "name": "getMoisSuivant",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getMoisSuivant"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AmajNbJustificatifs\u0028\u0029",
            "name": "majNbJustificatifs",
            "summary": "Met\u0020\u00E0\u0020jour\u0020le\u0020nombre\u0020de\u0020justificatifs\u0020de\u0020la\u0020table\u0020ficheFrais\npour\u0020le\u0020mois\u0020et\u0020le\u0020visiteur\u0020concern\u00E9",
            "url": "classes/PdoGsb.html#method_majNbJustificatifs"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AestPremierFraisMois\u0028\u0029",
            "name": "estPremierFraisMois",
            "summary": "Teste\u0020si\u0020un\u0020visiteur\u0020poss\u00E8de\u0020une\u0020fiche\u0020de\u0020frais\u0020pour\u0020le\u0020mois\u0020pass\u00E9\u0020en\u0020argument",
            "url": "classes/PdoGsb.html#method_estPremierFraisMois"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AdernierMoisSaisi\u0028\u0029",
            "name": "dernierMoisSaisi",
            "summary": "Retourne\u0020le\u0020dernier\u0020mois\u0020en\u0020cours\u0020d\u0027un\u0020visiteur",
            "url": "classes/PdoGsb.html#method_dernierMoisSaisi"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AcreeNouvellesLignesFrais\u0028\u0029",
            "name": "creeNouvellesLignesFrais",
            "summary": "Cr\u00E9e\u0020une\u0020nouvelle\u0020fiche\u0020de\u0020frais\u0020et\u0020les\u0020lignes\u0020de\u0020frais\u0020au\u0020forfait\npour\u0020un\u0020visiteur\u0020et\u0020un\u0020mois\u0020donn\u00E9s",
            "url": "classes/PdoGsb.html#method_creeNouvellesLignesFrais"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AcreeNouveauFraisHorsForfait\u0028\u0029",
            "name": "creeNouveauFraisHorsForfait",
            "summary": "Cr\u00E9e\u0020un\u0020nouveau\u0020frais\u0020hors\u0020forfait\u0020pour\u0020un\u0020visiteur\u0020un\u0020mois\u0020donn\u00E9\n\u00E0\u0020partir\u0020des\u0020informations\u0020fournies\u0020en\u0020param\u00E8tre",
            "url": "classes/PdoGsb.html#method_creeNouveauFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AsupprimerFraisHorsForfait\u0028\u0029",
            "name": "supprimerFraisHorsForfait",
            "summary": "Supprime\u0020le\u0020frais\u0020hors\u0020forfait\u0020dont\u0020l\u0027id\u0020est\u0020pass\u00E9\u0020en\u0020argument",
            "url": "classes/PdoGsb.html#method_supprimerFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetLesMoisDisponibles\u0028\u0029",
            "name": "getLesMoisDisponibles",
            "summary": "Retourne\u0020les\u0020mois\u0020pour\u0020lesquel\u0020un\u0020visiteur\u0020a\u0020une\u0020fiche\u0020de\u0020frais",
            "url": "classes/PdoGsb.html#method_getLesMoisDisponibles"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetLesMois\u0028\u0029",
            "name": "getLesMois",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getLesMois"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetVisiteursFromMois\u0028\u0029",
            "name": "getVisiteursFromMois",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getVisiteursFromMois"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetIdFromNomVisiteur\u0028\u0029",
            "name": "getIdFromNomVisiteur",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getIdFromNomVisiteur"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetLesInfosFicheFrais\u0028\u0029",
            "name": "getLesInfosFicheFrais",
            "summary": "Retourne\u0020les\u0020informations\u0020d\u0027une\u0020fiche\u0020de\u0020frais\u0020d\u0027un\u0020visiteur\u0020pour\u0020un\nmois\u0020donn\u00E9",
            "url": "classes/PdoGsb.html#method_getLesInfosFicheFrais"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AmajEtatFicheFrais\u0028\u0029",
            "name": "majEtatFicheFrais",
            "summary": "Modifie\u0020l\u0027\u00E9tat\u0020et\u0020la\u0020date\u0020de\u0020modification\u0020d\u0027une\u0020fiche\u0020de\u0020frais.",
            "url": "classes/PdoGsb.html#method_majEtatFicheFrais"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AreporterFraisHorsForfait\u0028\u0029",
            "name": "reporterFraisHorsForfait",
            "summary": "",
            "url": "classes/PdoGsb.html#method_reporterFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AvaliderFicheDeFrais\u0028\u0029",
            "name": "validerFicheDeFrais",
            "summary": "",
            "url": "classes/PdoGsb.html#method_validerFicheDeFrais"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AClotureFiche\u0028\u0029",
            "name": "ClotureFiche",
            "summary": "",
            "url": "classes/PdoGsb.html#method_ClotureFiche"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetNomPrenomVisiteur\u0028\u0029",
            "name": "getNomPrenomVisiteur",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getNomPrenomVisiteur"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetUtilisateursVA\u0028\u0029",
            "name": "getUtilisateursVA",
            "summary": "",
            "url": "classes/PdoGsb.html#method_getUtilisateursVA"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AgetLesMoisDisponiblesVA\u0028\u0029",
            "name": "getLesMoisDisponiblesVA",
            "summary": "Retourne\u0020la\u0020liste\u0020de\u0020mois\u0020pour\u0020lesquels\u0020unVisiteur\u0020\u00E0\u0020une\u0020fiche\nde\u0020frais\u0020valid\u00E9",
            "url": "classes/PdoGsb.html#method_getLesMoisDisponiblesVA"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003AestRefuse\u0028\u0029",
            "name": "estRefuse",
            "summary": "",
            "url": "classes/PdoGsb.html#method_estRefuse"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003A\u0024serveur",
            "name": "serveur",
            "summary": "",
            "url": "classes/PdoGsb.html#property_serveur"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003A\u0024bdd",
            "name": "bdd",
            "summary": "",
            "url": "classes/PdoGsb.html#property_bdd"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/PdoGsb.html#property_user"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003A\u0024mdp",
            "name": "mdp",
            "summary": "",
            "url": "classes/PdoGsb.html#property_mdp"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003A\u0024monPdo",
            "name": "monPdo",
            "summary": "",
            "url": "classes/PdoGsb.html#property_monPdo"
        },                {
            "fqsen": "\\PdoGsb\u003A\u003A\u0024monPdoGsb",
            "name": "monPdoGsb",
            "summary": "",
            "url": "classes/PdoGsb.html#property_monPdoGsb"
        },                {
            "fqsen": "\\estConnecte\u0028\u0029",
            "name": "estConnecte",
            "summary": "Teste\u0020si\u0020un\u0020quelconque\u0020visiteur\u0020est\u0020connect\u00E9",
            "url": "namespaces/default.html#function_estConnecte"
        },                {
            "fqsen": "\\estConnecteComptable\u0028\u0029",
            "name": "estConnecteComptable",
            "summary": "",
            "url": "namespaces/default.html#function_estConnecteComptable"
        },                {
            "fqsen": "\\connecter\u0028\u0029",
            "name": "connecter",
            "summary": "Enregistre\u0020dans\u0020une\u0020variable\u0020session\u0020les\u0020infos\u0020d\u0027un\u0020visiteur",
            "url": "namespaces/default.html#function_connecter"
        },                {
            "fqsen": "\\connecterComptable\u0028\u0029",
            "name": "connecterComptable",
            "summary": "",
            "url": "namespaces/default.html#function_connecterComptable"
        },                {
            "fqsen": "\\deconnecter\u0028\u0029",
            "name": "deconnecter",
            "summary": "D\u00E9truit\u0020la\u0020session\u0020active",
            "url": "namespaces/default.html#function_deconnecter"
        },                {
            "fqsen": "\\dateFrancaisVersAnglais\u0028\u0029",
            "name": "dateFrancaisVersAnglais",
            "summary": "Transforme\u0020une\u0020date\u0020au\u0020format\u0020fran\u00E7ais\u0020jj\/mm\/aaaa\u0020vers\u0020le\u0020format\u0020anglais\naaaa\u002Dmm\u002Djj",
            "url": "namespaces/default.html#function_dateFrancaisVersAnglais"
        },                {
            "fqsen": "\\dateAnglaisVersFrancais\u0028\u0029",
            "name": "dateAnglaisVersFrancais",
            "summary": "Transforme\u0020une\u0020date\u0020au\u0020format\u0020format\u0020anglais\u0020aaaa\u002Dmm\u002Djj\u0020vers\u0020le\u0020format\nfran\u00E7ais\u0020jj\/mm\/aaaa",
            "url": "namespaces/default.html#function_dateAnglaisVersFrancais"
        },                {
            "fqsen": "\\getMois\u0028\u0029",
            "name": "getMois",
            "summary": "Fonction\u0020qui\u0020retourne\u0020le\u0020mois\u0020\u0028au\u0020format\u0020ID\u0020GSB\u0020\u003A\u0020aaaamm\u0029\u0020\u00E0\u0020partir\u0020d\u0027une\ndate\u0020pass\u00E9e\u0020en\u0020param\u00E8tre",
            "url": "namespaces/default.html#function_getMois"
        },                {
            "fqsen": "\\getMoisSuivant\u0028\u0029",
            "name": "getMoisSuivant",
            "summary": "Fonction\u0020qui\u0020retourne\u0020le\u0020mois\u0020suivant\u0020un\u0020mois\u0020pass\u00E9\u0020en\u0020param\u00E8tre",
            "url": "namespaces/default.html#function_getMoisSuivant"
        },                {
            "fqsen": "\\estEntierPositif\u0028\u0029",
            "name": "estEntierPositif",
            "summary": "Indique\u0020si\u0020une\u0020valeur\u0020est\u0020un\u0020entier\u0020positif\u0020ou\u0020nul",
            "url": "namespaces/default.html#function_estEntierPositif"
        },                {
            "fqsen": "\\estTableauEntiers\u0028\u0029",
            "name": "estTableauEntiers",
            "summary": "Indique\u0020si\u0020un\u0020tableau\u0020de\u0020valeurs\u0020est\u0020constitu\u00E9\u0020d\u0027entiers\u0020positifs\u0020ou\u0020nuls",
            "url": "namespaces/default.html#function_estTableauEntiers"
        },                {
            "fqsen": "\\estDateDepassee\u0028\u0029",
            "name": "estDateDepassee",
            "summary": "V\u00E9rifie\u0020si\u0020une\u0020date\u0020est\u0020inf\u00E9rieure\u0020d\u0027un\u0020an\u0020\u00E0\u0020la\u0020date\u0020actuelle",
            "url": "namespaces/default.html#function_estDateDepassee"
        },                {
            "fqsen": "\\estDateValide\u0028\u0029",
            "name": "estDateValide",
            "summary": "V\u00E9rifie\u0020la\u0020validit\u00E9\u0020du\u0020format\u0020d\u0027une\u0020date\u0020fran\u00E7aise\u0020jj\/mm\/aaaa",
            "url": "namespaces/default.html#function_estDateValide"
        },                {
            "fqsen": "\\lesQteFraisValides\u0028\u0029",
            "name": "lesQteFraisValides",
            "summary": "V\u00E9rifie\u0020que\u0020le\u0020tableau\u0020de\u0020frais\u0020ne\u0020contient\u0020que\u0020des\u0020valeurs\u0020num\u00E9riques",
            "url": "namespaces/default.html#function_lesQteFraisValides"
        },                {
            "fqsen": "\\valideInfosFrais\u0028\u0029",
            "name": "valideInfosFrais",
            "summary": "V\u00E9rifie\u0020la\u0020validit\u00E9\u0020des\u0020trois\u0020arguments\u0020\u003A\u0020la\u0020date,\u0020le\u0020libell\u00E9\u0020du\u0020frais\net\u0020le\u0020montant",
            "url": "namespaces/default.html#function_valideInfosFrais"
        },                {
            "fqsen": "\\ajouterErreur\u0028\u0029",
            "name": "ajouterErreur",
            "summary": "Ajoute\u0020le\u0020libell\u00E9\u0020d\u0027une\u0020erreur\u0020au\u0020tableau\u0020des\u0020erreurs",
            "url": "namespaces/default.html#function_ajouterErreur"
        },                {
            "fqsen": "\\nbErreurs\u0028\u0029",
            "name": "nbErreurs",
            "summary": "Retoune\u0020le\u0020nombre\u0020de\u0020lignes\u0020du\u0020tableau\u0020des\u0020erreurs",
            "url": "namespaces/default.html#function_nbErreurs"
        },                {
            "fqsen": "\\connecterA2f\u0028\u0029",
            "name": "connecterA2f",
            "summary": "",
            "url": "namespaces/default.html#function_connecterA2f"
        },                {
            "fqsen": "\\FPDF_VERSION",
            "name": "FPDF_VERSION",
            "summary": "",
            "url": "namespaces/default.html#constant_FPDF_VERSION"
        },                {
            "fqsen": "\\FPDF",
            "name": "FPDF",
            "summary": "",
            "url": "classes/FPDF.html"
        },                {
            "fqsen": "\\FPDF\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/FPDF.html#method___construct"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetMargins\u0028\u0029",
            "name": "SetMargins",
            "summary": "",
            "url": "classes/FPDF.html#method_SetMargins"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetLeftMargin\u0028\u0029",
            "name": "SetLeftMargin",
            "summary": "",
            "url": "classes/FPDF.html#method_SetLeftMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetTopMargin\u0028\u0029",
            "name": "SetTopMargin",
            "summary": "",
            "url": "classes/FPDF.html#method_SetTopMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetRightMargin\u0028\u0029",
            "name": "SetRightMargin",
            "summary": "",
            "url": "classes/FPDF.html#method_SetRightMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetAutoPageBreak\u0028\u0029",
            "name": "SetAutoPageBreak",
            "summary": "",
            "url": "classes/FPDF.html#method_SetAutoPageBreak"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetDisplayMode\u0028\u0029",
            "name": "SetDisplayMode",
            "summary": "",
            "url": "classes/FPDF.html#method_SetDisplayMode"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetCompression\u0028\u0029",
            "name": "SetCompression",
            "summary": "",
            "url": "classes/FPDF.html#method_SetCompression"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetTitle\u0028\u0029",
            "name": "SetTitle",
            "summary": "",
            "url": "classes/FPDF.html#method_SetTitle"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetAuthor\u0028\u0029",
            "name": "SetAuthor",
            "summary": "",
            "url": "classes/FPDF.html#method_SetAuthor"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetSubject\u0028\u0029",
            "name": "SetSubject",
            "summary": "",
            "url": "classes/FPDF.html#method_SetSubject"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetKeywords\u0028\u0029",
            "name": "SetKeywords",
            "summary": "",
            "url": "classes/FPDF.html#method_SetKeywords"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetCreator\u0028\u0029",
            "name": "SetCreator",
            "summary": "",
            "url": "classes/FPDF.html#method_SetCreator"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024AliasNbPages",
            "name": "AliasNbPages",
            "summary": "",
            "url": "classes/FPDF.html#property_AliasNbPages"
        },                {
            "fqsen": "\\FPDF\u003A\u003AError\u0028\u0029",
            "name": "Error",
            "summary": "",
            "url": "classes/FPDF.html#method_Error"
        },                {
            "fqsen": "\\FPDF\u003A\u003AClose\u0028\u0029",
            "name": "Close",
            "summary": "",
            "url": "classes/FPDF.html#method_Close"
        },                {
            "fqsen": "\\FPDF\u003A\u003AAddPage\u0028\u0029",
            "name": "AddPage",
            "summary": "",
            "url": "classes/FPDF.html#method_AddPage"
        },                {
            "fqsen": "\\FPDF\u003A\u003AHeader\u0028\u0029",
            "name": "Header",
            "summary": "",
            "url": "classes/FPDF.html#method_Header"
        },                {
            "fqsen": "\\FPDF\u003A\u003AFooter\u0028\u0029",
            "name": "Footer",
            "summary": "",
            "url": "classes/FPDF.html#method_Footer"
        },                {
            "fqsen": "\\FPDF\u003A\u003APageNo\u0028\u0029",
            "name": "PageNo",
            "summary": "",
            "url": "classes/FPDF.html#method_PageNo"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetDrawColor\u0028\u0029",
            "name": "SetDrawColor",
            "summary": "",
            "url": "classes/FPDF.html#method_SetDrawColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetFillColor\u0028\u0029",
            "name": "SetFillColor",
            "summary": "",
            "url": "classes/FPDF.html#method_SetFillColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetTextColor\u0028\u0029",
            "name": "SetTextColor",
            "summary": "",
            "url": "classes/FPDF.html#method_SetTextColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetStringWidth\u0028\u0029",
            "name": "GetStringWidth",
            "summary": "",
            "url": "classes/FPDF.html#method_GetStringWidth"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetLineWidth\u0028\u0029",
            "name": "SetLineWidth",
            "summary": "",
            "url": "classes/FPDF.html#method_SetLineWidth"
        },                {
            "fqsen": "\\FPDF\u003A\u003ALine\u0028\u0029",
            "name": "Line",
            "summary": "",
            "url": "classes/FPDF.html#method_Line"
        },                {
            "fqsen": "\\FPDF\u003A\u003ARect\u0028\u0029",
            "name": "Rect",
            "summary": "",
            "url": "classes/FPDF.html#method_Rect"
        },                {
            "fqsen": "\\FPDF\u003A\u003AAddFont\u0028\u0029",
            "name": "AddFont",
            "summary": "",
            "url": "classes/FPDF.html#method_AddFont"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetFont\u0028\u0029",
            "name": "SetFont",
            "summary": "",
            "url": "classes/FPDF.html#method_SetFont"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetFontSize\u0028\u0029",
            "name": "SetFontSize",
            "summary": "",
            "url": "classes/FPDF.html#method_SetFontSize"
        },                {
            "fqsen": "\\FPDF\u003A\u003AAddLink\u0028\u0029",
            "name": "AddLink",
            "summary": "",
            "url": "classes/FPDF.html#method_AddLink"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetLink\u0028\u0029",
            "name": "SetLink",
            "summary": "",
            "url": "classes/FPDF.html#method_SetLink"
        },                {
            "fqsen": "\\FPDF\u003A\u003ALink\u0028\u0029",
            "name": "Link",
            "summary": "",
            "url": "classes/FPDF.html#method_Link"
        },                {
            "fqsen": "\\FPDF\u003A\u003AText\u0028\u0029",
            "name": "Text",
            "summary": "",
            "url": "classes/FPDF.html#method_Text"
        },                {
            "fqsen": "\\FPDF\u003A\u003AAcceptPageBreak\u0028\u0029",
            "name": "AcceptPageBreak",
            "summary": "",
            "url": "classes/FPDF.html#method_AcceptPageBreak"
        },                {
            "fqsen": "\\FPDF\u003A\u003ACell\u0028\u0029",
            "name": "Cell",
            "summary": "",
            "url": "classes/FPDF.html#method_Cell"
        },                {
            "fqsen": "\\FPDF\u003A\u003AMultiCell\u0028\u0029",
            "name": "MultiCell",
            "summary": "",
            "url": "classes/FPDF.html#method_MultiCell"
        },                {
            "fqsen": "\\FPDF\u003A\u003AWrite\u0028\u0029",
            "name": "Write",
            "summary": "",
            "url": "classes/FPDF.html#method_Write"
        },                {
            "fqsen": "\\FPDF\u003A\u003ALn\u0028\u0029",
            "name": "Ln",
            "summary": "",
            "url": "classes/FPDF.html#method_Ln"
        },                {
            "fqsen": "\\FPDF\u003A\u003AImage\u0028\u0029",
            "name": "Image",
            "summary": "",
            "url": "classes/FPDF.html#method_Image"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetPageWidth\u0028\u0029",
            "name": "GetPageWidth",
            "summary": "",
            "url": "classes/FPDF.html#method_GetPageWidth"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetPageHeight\u0028\u0029",
            "name": "GetPageHeight",
            "summary": "",
            "url": "classes/FPDF.html#method_GetPageHeight"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetX\u0028\u0029",
            "name": "GetX",
            "summary": "",
            "url": "classes/FPDF.html#method_GetX"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetX\u0028\u0029",
            "name": "SetX",
            "summary": "",
            "url": "classes/FPDF.html#method_SetX"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetY\u0028\u0029",
            "name": "GetY",
            "summary": "",
            "url": "classes/FPDF.html#method_GetY"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetY\u0028\u0029",
            "name": "SetY",
            "summary": "",
            "url": "classes/FPDF.html#method_SetY"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetXY\u0028\u0029",
            "name": "SetXY",
            "summary": "",
            "url": "classes/FPDF.html#method_SetXY"
        },                {
            "fqsen": "\\FPDF\u003A\u003AOutput\u0028\u0029",
            "name": "Output",
            "summary": "",
            "url": "classes/FPDF.html#method_Output"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_dochecks\u0028\u0029",
            "name": "_dochecks",
            "summary": "",
            "url": "classes/FPDF.html#method__dochecks"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_checkoutput\u0028\u0029",
            "name": "_checkoutput",
            "summary": "",
            "url": "classes/FPDF.html#method__checkoutput"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_getpagesize\u0028\u0029",
            "name": "_getpagesize",
            "summary": "",
            "url": "classes/FPDF.html#method__getpagesize"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_beginpage\u0028\u0029",
            "name": "_beginpage",
            "summary": "",
            "url": "classes/FPDF.html#method__beginpage"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_endpage\u0028\u0029",
            "name": "_endpage",
            "summary": "",
            "url": "classes/FPDF.html#method__endpage"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_loadfont\u0028\u0029",
            "name": "_loadfont",
            "summary": "",
            "url": "classes/FPDF.html#method__loadfont"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_isascii\u0028\u0029",
            "name": "_isascii",
            "summary": "",
            "url": "classes/FPDF.html#method__isascii"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_httpencode\u0028\u0029",
            "name": "_httpencode",
            "summary": "",
            "url": "classes/FPDF.html#method__httpencode"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_UTF8toUTF16\u0028\u0029",
            "name": "_UTF8toUTF16",
            "summary": "",
            "url": "classes/FPDF.html#method__UTF8toUTF16"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_escape\u0028\u0029",
            "name": "_escape",
            "summary": "",
            "url": "classes/FPDF.html#method__escape"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_textstring\u0028\u0029",
            "name": "_textstring",
            "summary": "",
            "url": "classes/FPDF.html#method__textstring"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_dounderline\u0028\u0029",
            "name": "_dounderline",
            "summary": "",
            "url": "classes/FPDF.html#method__dounderline"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_parsejpg\u0028\u0029",
            "name": "_parsejpg",
            "summary": "",
            "url": "classes/FPDF.html#method__parsejpg"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_parsepng\u0028\u0029",
            "name": "_parsepng",
            "summary": "",
            "url": "classes/FPDF.html#method__parsepng"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_parsepngstream\u0028\u0029",
            "name": "_parsepngstream",
            "summary": "",
            "url": "classes/FPDF.html#method__parsepngstream"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_readstream\u0028\u0029",
            "name": "_readstream",
            "summary": "",
            "url": "classes/FPDF.html#method__readstream"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_readint\u0028\u0029",
            "name": "_readint",
            "summary": "",
            "url": "classes/FPDF.html#method__readint"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_parsegif\u0028\u0029",
            "name": "_parsegif",
            "summary": "",
            "url": "classes/FPDF.html#method__parsegif"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_out\u0028\u0029",
            "name": "_out",
            "summary": "",
            "url": "classes/FPDF.html#method__out"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_put\u0028\u0029",
            "name": "_put",
            "summary": "",
            "url": "classes/FPDF.html#method__put"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_getoffset\u0028\u0029",
            "name": "_getoffset",
            "summary": "",
            "url": "classes/FPDF.html#method__getoffset"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_newobj\u0028\u0029",
            "name": "_newobj",
            "summary": "",
            "url": "classes/FPDF.html#method__newobj"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putstream\u0028\u0029",
            "name": "_putstream",
            "summary": "",
            "url": "classes/FPDF.html#method__putstream"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putstreamobject\u0028\u0029",
            "name": "_putstreamobject",
            "summary": "",
            "url": "classes/FPDF.html#method__putstreamobject"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putpage\u0028\u0029",
            "name": "_putpage",
            "summary": "",
            "url": "classes/FPDF.html#method__putpage"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putpages\u0028\u0029",
            "name": "_putpages",
            "summary": "",
            "url": "classes/FPDF.html#method__putpages"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putfonts\u0028\u0029",
            "name": "_putfonts",
            "summary": "",
            "url": "classes/FPDF.html#method__putfonts"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_tounicodecmap\u0028\u0029",
            "name": "_tounicodecmap",
            "summary": "",
            "url": "classes/FPDF.html#method__tounicodecmap"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putimages\u0028\u0029",
            "name": "_putimages",
            "summary": "",
            "url": "classes/FPDF.html#method__putimages"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putimage\u0028\u0029",
            "name": "_putimage",
            "summary": "",
            "url": "classes/FPDF.html#method__putimage"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putxobjectdict\u0028\u0029",
            "name": "_putxobjectdict",
            "summary": "",
            "url": "classes/FPDF.html#method__putxobjectdict"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putresourcedict\u0028\u0029",
            "name": "_putresourcedict",
            "summary": "",
            "url": "classes/FPDF.html#method__putresourcedict"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putresources\u0028\u0029",
            "name": "_putresources",
            "summary": "",
            "url": "classes/FPDF.html#method__putresources"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putinfo\u0028\u0029",
            "name": "_putinfo",
            "summary": "",
            "url": "classes/FPDF.html#method__putinfo"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putcatalog\u0028\u0029",
            "name": "_putcatalog",
            "summary": "",
            "url": "classes/FPDF.html#method__putcatalog"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putheader\u0028\u0029",
            "name": "_putheader",
            "summary": "",
            "url": "classes/FPDF.html#method__putheader"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_puttrailer\u0028\u0029",
            "name": "_puttrailer",
            "summary": "",
            "url": "classes/FPDF.html#method__puttrailer"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_enddoc\u0028\u0029",
            "name": "_enddoc",
            "summary": "",
            "url": "classes/FPDF.html#method__enddoc"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/FPDF.html#property_page"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024n",
            "name": "n",
            "summary": "",
            "url": "classes/FPDF.html#property_n"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024offsets",
            "name": "offsets",
            "summary": "",
            "url": "classes/FPDF.html#property_offsets"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024buffer",
            "name": "buffer",
            "summary": "",
            "url": "classes/FPDF.html#property_buffer"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024pages",
            "name": "pages",
            "summary": "",
            "url": "classes/FPDF.html#property_pages"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/FPDF.html#property_state"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024compress",
            "name": "compress",
            "summary": "",
            "url": "classes/FPDF.html#property_compress"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024k",
            "name": "k",
            "summary": "",
            "url": "classes/FPDF.html#property_k"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024DefOrientation",
            "name": "DefOrientation",
            "summary": "",
            "url": "classes/FPDF.html#property_DefOrientation"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CurOrientation",
            "name": "CurOrientation",
            "summary": "",
            "url": "classes/FPDF.html#property_CurOrientation"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024StdPageSizes",
            "name": "StdPageSizes",
            "summary": "",
            "url": "classes/FPDF.html#property_StdPageSizes"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024DefPageSize",
            "name": "DefPageSize",
            "summary": "",
            "url": "classes/FPDF.html#property_DefPageSize"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CurPageSize",
            "name": "CurPageSize",
            "summary": "",
            "url": "classes/FPDF.html#property_CurPageSize"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CurRotation",
            "name": "CurRotation",
            "summary": "",
            "url": "classes/FPDF.html#property_CurRotation"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024PageInfo",
            "name": "PageInfo",
            "summary": "",
            "url": "classes/FPDF.html#property_PageInfo"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024wPt",
            "name": "wPt",
            "summary": "",
            "url": "classes/FPDF.html#property_wPt"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024hPt",
            "name": "hPt",
            "summary": "",
            "url": "classes/FPDF.html#property_hPt"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024w",
            "name": "w",
            "summary": "",
            "url": "classes/FPDF.html#property_w"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024h",
            "name": "h",
            "summary": "",
            "url": "classes/FPDF.html#property_h"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024lMargin",
            "name": "lMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_lMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024tMargin",
            "name": "tMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_tMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024rMargin",
            "name": "rMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_rMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024bMargin",
            "name": "bMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_bMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024cMargin",
            "name": "cMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_cMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024x",
            "name": "x",
            "summary": "",
            "url": "classes/FPDF.html#property_x"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024y",
            "name": "y",
            "summary": "",
            "url": "classes/FPDF.html#property_y"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024lasth",
            "name": "lasth",
            "summary": "",
            "url": "classes/FPDF.html#property_lasth"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024LineWidth",
            "name": "LineWidth",
            "summary": "",
            "url": "classes/FPDF.html#property_LineWidth"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024fontpath",
            "name": "fontpath",
            "summary": "",
            "url": "classes/FPDF.html#property_fontpath"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CoreFonts",
            "name": "CoreFonts",
            "summary": "",
            "url": "classes/FPDF.html#property_CoreFonts"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024fonts",
            "name": "fonts",
            "summary": "",
            "url": "classes/FPDF.html#property_fonts"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontFiles",
            "name": "FontFiles",
            "summary": "",
            "url": "classes/FPDF.html#property_FontFiles"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024encodings",
            "name": "encodings",
            "summary": "",
            "url": "classes/FPDF.html#property_encodings"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024cmaps",
            "name": "cmaps",
            "summary": "",
            "url": "classes/FPDF.html#property_cmaps"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontFamily",
            "name": "FontFamily",
            "summary": "",
            "url": "classes/FPDF.html#property_FontFamily"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontStyle",
            "name": "FontStyle",
            "summary": "",
            "url": "classes/FPDF.html#property_FontStyle"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024underline",
            "name": "underline",
            "summary": "",
            "url": "classes/FPDF.html#property_underline"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CurrentFont",
            "name": "CurrentFont",
            "summary": "",
            "url": "classes/FPDF.html#property_CurrentFont"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontSizePt",
            "name": "FontSizePt",
            "summary": "",
            "url": "classes/FPDF.html#property_FontSizePt"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontSize",
            "name": "FontSize",
            "summary": "",
            "url": "classes/FPDF.html#property_FontSize"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024DrawColor",
            "name": "DrawColor",
            "summary": "",
            "url": "classes/FPDF.html#property_DrawColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FillColor",
            "name": "FillColor",
            "summary": "",
            "url": "classes/FPDF.html#property_FillColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024TextColor",
            "name": "TextColor",
            "summary": "",
            "url": "classes/FPDF.html#property_TextColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024ColorFlag",
            "name": "ColorFlag",
            "summary": "",
            "url": "classes/FPDF.html#property_ColorFlag"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024WithAlpha",
            "name": "WithAlpha",
            "summary": "",
            "url": "classes/FPDF.html#property_WithAlpha"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024ws",
            "name": "ws",
            "summary": "",
            "url": "classes/FPDF.html#property_ws"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024images",
            "name": "images",
            "summary": "",
            "url": "classes/FPDF.html#property_images"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024PageLinks",
            "name": "PageLinks",
            "summary": "",
            "url": "classes/FPDF.html#property_PageLinks"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024links",
            "name": "links",
            "summary": "",
            "url": "classes/FPDF.html#property_links"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024AutoPageBreak",
            "name": "AutoPageBreak",
            "summary": "",
            "url": "classes/FPDF.html#property_AutoPageBreak"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024PageBreakTrigger",
            "name": "PageBreakTrigger",
            "summary": "",
            "url": "classes/FPDF.html#property_PageBreakTrigger"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024InHeader",
            "name": "InHeader",
            "summary": "",
            "url": "classes/FPDF.html#property_InHeader"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024InFooter",
            "name": "InFooter",
            "summary": "",
            "url": "classes/FPDF.html#property_InFooter"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024ZoomMode",
            "name": "ZoomMode",
            "summary": "",
            "url": "classes/FPDF.html#property_ZoomMode"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024LayoutMode",
            "name": "LayoutMode",
            "summary": "",
            "url": "classes/FPDF.html#property_LayoutMode"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/FPDF.html#property_metadata"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024PDFVersion",
            "name": "PDFVersion",
            "summary": "",
            "url": "classes/FPDF.html#property_PDFVersion"
        },                {
            "fqsen": "\\Message\u0028\u0029",
            "name": "Message",
            "summary": "",
            "url": "namespaces/default.html#function_Message"
        },                {
            "fqsen": "\\Notice\u0028\u0029",
            "name": "Notice",
            "summary": "",
            "url": "namespaces/default.html#function_Notice"
        },                {
            "fqsen": "\\Warning\u0028\u0029",
            "name": "Warning",
            "summary": "",
            "url": "namespaces/default.html#function_Warning"
        },                {
            "fqsen": "\\Error\u0028\u0029",
            "name": "Error",
            "summary": "",
            "url": "namespaces/default.html#function_Error"
        },                {
            "fqsen": "\\LoadMap\u0028\u0029",
            "name": "LoadMap",
            "summary": "",
            "url": "namespaces/default.html#function_LoadMap"
        },                {
            "fqsen": "\\GetInfoFromTrueType\u0028\u0029",
            "name": "GetInfoFromTrueType",
            "summary": "",
            "url": "namespaces/default.html#function_GetInfoFromTrueType"
        },                {
            "fqsen": "\\GetInfoFromType1\u0028\u0029",
            "name": "GetInfoFromType1",
            "summary": "",
            "url": "namespaces/default.html#function_GetInfoFromType1"
        },                {
            "fqsen": "\\MakeFontDescriptor\u0028\u0029",
            "name": "MakeFontDescriptor",
            "summary": "",
            "url": "namespaces/default.html#function_MakeFontDescriptor"
        },                {
            "fqsen": "\\MakeWidthArray\u0028\u0029",
            "name": "MakeWidthArray",
            "summary": "",
            "url": "namespaces/default.html#function_MakeWidthArray"
        },                {
            "fqsen": "\\MakeFontEncoding\u0028\u0029",
            "name": "MakeFontEncoding",
            "summary": "",
            "url": "namespaces/default.html#function_MakeFontEncoding"
        },                {
            "fqsen": "\\MakeUnicodeArray\u0028\u0029",
            "name": "MakeUnicodeArray",
            "summary": "",
            "url": "namespaces/default.html#function_MakeUnicodeArray"
        },                {
            "fqsen": "\\SaveToFile\u0028\u0029",
            "name": "SaveToFile",
            "summary": "",
            "url": "namespaces/default.html#function_SaveToFile"
        },                {
            "fqsen": "\\MakeDefinitionFile\u0028\u0029",
            "name": "MakeDefinitionFile",
            "summary": "",
            "url": "namespaces/default.html#function_MakeDefinitionFile"
        },                {
            "fqsen": "\\MakeFont\u0028\u0029",
            "name": "MakeFont",
            "summary": "",
            "url": "namespaces/default.html#function_MakeFont"
        },                {
            "fqsen": "\\TTFParser",
            "name": "TTFParser",
            "summary": "",
            "url": "classes/TTFParser.html"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/TTFParser.html#method___construct"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/TTFParser.html#method___destruct"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParse\u0028\u0029",
            "name": "Parse",
            "summary": "",
            "url": "classes/TTFParser.html#method_Parse"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseOffsetTable\u0028\u0029",
            "name": "ParseOffsetTable",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseOffsetTable"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseHead\u0028\u0029",
            "name": "ParseHead",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseHead"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseHhea\u0028\u0029",
            "name": "ParseHhea",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseHhea"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseMaxp\u0028\u0029",
            "name": "ParseMaxp",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseMaxp"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseHmtx\u0028\u0029",
            "name": "ParseHmtx",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseHmtx"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseLoca\u0028\u0029",
            "name": "ParseLoca",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseLoca"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseGlyf\u0028\u0029",
            "name": "ParseGlyf",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseGlyf"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseCmap\u0028\u0029",
            "name": "ParseCmap",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseCmap"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseName\u0028\u0029",
            "name": "ParseName",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseName"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseOS2\u0028\u0029",
            "name": "ParseOS2",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseOS2"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParsePost\u0028\u0029",
            "name": "ParsePost",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParsePost"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ASubset\u0028\u0029",
            "name": "Subset",
            "summary": "",
            "url": "classes/TTFParser.html#method_Subset"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AAddGlyph\u0028\u0029",
            "name": "AddGlyph",
            "summary": "",
            "url": "classes/TTFParser.html#method_AddGlyph"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuild\u0028\u0029",
            "name": "Build",
            "summary": "",
            "url": "classes/TTFParser.html#method_Build"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildCmap\u0028\u0029",
            "name": "BuildCmap",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildCmap"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildHhea\u0028\u0029",
            "name": "BuildHhea",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildHhea"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildHmtx\u0028\u0029",
            "name": "BuildHmtx",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildHmtx"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildLoca\u0028\u0029",
            "name": "BuildLoca",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildLoca"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildGlyf\u0028\u0029",
            "name": "BuildGlyf",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildGlyf"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildMaxp\u0028\u0029",
            "name": "BuildMaxp",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildMaxp"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildPost\u0028\u0029",
            "name": "BuildPost",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildPost"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildFont\u0028\u0029",
            "name": "BuildFont",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildFont"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ALoadTable\u0028\u0029",
            "name": "LoadTable",
            "summary": "",
            "url": "classes/TTFParser.html#method_LoadTable"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ASetTable\u0028\u0029",
            "name": "SetTable",
            "summary": "",
            "url": "classes/TTFParser.html#method_SetTable"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ASeek\u0028\u0029",
            "name": "Seek",
            "summary": "",
            "url": "classes/TTFParser.html#method_Seek"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ASkip\u0028\u0029",
            "name": "Skip",
            "summary": "",
            "url": "classes/TTFParser.html#method_Skip"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ARead\u0028\u0029",
            "name": "Read",
            "summary": "",
            "url": "classes/TTFParser.html#method_Read"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AReadUShort\u0028\u0029",
            "name": "ReadUShort",
            "summary": "",
            "url": "classes/TTFParser.html#method_ReadUShort"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AReadShort\u0028\u0029",
            "name": "ReadShort",
            "summary": "",
            "url": "classes/TTFParser.html#method_ReadShort"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AReadULong\u0028\u0029",
            "name": "ReadULong",
            "summary": "",
            "url": "classes/TTFParser.html#method_ReadULong"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ACheckSum\u0028\u0029",
            "name": "CheckSum",
            "summary": "",
            "url": "classes/TTFParser.html#method_CheckSum"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AError\u0028\u0029",
            "name": "Error",
            "summary": "",
            "url": "classes/TTFParser.html#method_Error"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024f",
            "name": "f",
            "summary": "",
            "url": "classes/TTFParser.html#property_f"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024tables",
            "name": "tables",
            "summary": "",
            "url": "classes/TTFParser.html#property_tables"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024numberOfHMetrics",
            "name": "numberOfHMetrics",
            "summary": "",
            "url": "classes/TTFParser.html#property_numberOfHMetrics"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024numGlyphs",
            "name": "numGlyphs",
            "summary": "",
            "url": "classes/TTFParser.html#property_numGlyphs"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024glyphNames",
            "name": "glyphNames",
            "summary": "",
            "url": "classes/TTFParser.html#property_glyphNames"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024indexToLocFormat",
            "name": "indexToLocFormat",
            "summary": "",
            "url": "classes/TTFParser.html#property_indexToLocFormat"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024subsettedChars",
            "name": "subsettedChars",
            "summary": "",
            "url": "classes/TTFParser.html#property_subsettedChars"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024subsettedGlyphs",
            "name": "subsettedGlyphs",
            "summary": "",
            "url": "classes/TTFParser.html#property_subsettedGlyphs"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024chars",
            "name": "chars",
            "summary": "",
            "url": "classes/TTFParser.html#property_chars"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024glyphs",
            "name": "glyphs",
            "summary": "",
            "url": "classes/TTFParser.html#property_glyphs"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024unitsPerEm",
            "name": "unitsPerEm",
            "summary": "",
            "url": "classes/TTFParser.html#property_unitsPerEm"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024xMin",
            "name": "xMin",
            "summary": "",
            "url": "classes/TTFParser.html#property_xMin"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024yMin",
            "name": "yMin",
            "summary": "",
            "url": "classes/TTFParser.html#property_yMin"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024xMax",
            "name": "xMax",
            "summary": "",
            "url": "classes/TTFParser.html#property_xMax"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024yMax",
            "name": "yMax",
            "summary": "",
            "url": "classes/TTFParser.html#property_yMax"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024postScriptName",
            "name": "postScriptName",
            "summary": "",
            "url": "classes/TTFParser.html#property_postScriptName"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024embeddable",
            "name": "embeddable",
            "summary": "",
            "url": "classes/TTFParser.html#property_embeddable"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024bold",
            "name": "bold",
            "summary": "",
            "url": "classes/TTFParser.html#property_bold"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024typoAscender",
            "name": "typoAscender",
            "summary": "",
            "url": "classes/TTFParser.html#property_typoAscender"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024typoDescender",
            "name": "typoDescender",
            "summary": "",
            "url": "classes/TTFParser.html#property_typoDescender"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024capHeight",
            "name": "capHeight",
            "summary": "",
            "url": "classes/TTFParser.html#property_capHeight"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024italicAngle",
            "name": "italicAngle",
            "summary": "",
            "url": "classes/TTFParser.html#property_italicAngle"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024underlinePosition",
            "name": "underlinePosition",
            "summary": "",
            "url": "classes/TTFParser.html#property_underlinePosition"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024underlineThickness",
            "name": "underlineThickness",
            "summary": "",
            "url": "classes/TTFParser.html#property_underlineThickness"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024isFixedPitch",
            "name": "isFixedPitch",
            "summary": "",
            "url": "classes/TTFParser.html#property_isFixedPitch"
        },                {
            "fqsen": "\\entete_table\u0028\u0029",
            "name": "entete_table",
            "summary": "",
            "url": "namespaces/default.html#function_entete_table"
        },                {
            "fqsen": "\\entete_table2\u0028\u0029",
            "name": "entete_table2",
            "summary": "",
            "url": "namespaces/default.html#function_entete_table2"
        },                {
            "fqsen": "\\PDF",
            "name": "PDF",
            "summary": "",
            "url": "classes/PDF.html"
        },                {
            "fqsen": "\\PDF\u003A\u003AHeader\u0028\u0029",
            "name": "Header",
            "summary": "",
            "url": "classes/PDF.html#method_Header"
        },                {
            "fqsen": "\\PDF\u003A\u003AFooter\u0028\u0029",
            "name": "Footer",
            "summary": "",
            "url": "classes/PDF.html#method_Footer"
        },                {
            "fqsen": "\\FPDF_FONTPATH",
            "name": "FPDF_FONTPATH",
            "summary": "",
            "url": "namespaces/default.html#constant_FPDF_FONTPATH"
        },                {
            "fqsen": "\\getLesVisiteurs\u0028\u0029",
            "name": "getLesVisiteurs",
            "summary": "",
            "url": "namespaces/default.html#function_getLesVisiteurs"
        },                {
            "fqsen": "\\getNbTable\u0028\u0029",
            "name": "getNbTable",
            "summary": "Fonction\u0020g\u00E9n\u00E9rique\u0020qui\u0020retourne\u0020le\u0020nombre\u0020d\u0027enregistrements\u0020d\u0027une\u0020table",
            "url": "namespaces/default.html#function_getNbTable"
        },                {
            "fqsen": "\\getLesFichesFrais\u0028\u0029",
            "name": "getLesFichesFrais",
            "summary": "Fonction\u0020qui\u0020retourne\u0020la\u0020liste\u0020des\u0020fiches\u0020de\u0020frais",
            "url": "namespaces/default.html#function_getLesFichesFrais"
        },                {
            "fqsen": "\\getLesIdFraisForfait\u0028\u0029",
            "name": "getLesIdFraisForfait",
            "summary": "Fonction\u0020qui\u0020retourne\u0020les\u0020id\u0020des\u0020fiches\u0020de\u0020frais",
            "url": "namespaces/default.html#function_getLesIdFraisForfait"
        },                {
            "fqsen": "\\getMoisPrecedent\u0028\u0029",
            "name": "getMoisPrecedent",
            "summary": "Fonction\u0020qui\u0020retourne\u0020le\u0020mois\u0020pr\u00E9c\u00E9dent\u0020un\u0020mois\u0020pass\u00E9\u0020en\u0020param\u00E8tre",
            "url": "namespaces/default.html#function_getMoisPrecedent"
        },                {
            "fqsen": "\\creationFichesFrais\u0028\u0029",
            "name": "creationFichesFrais",
            "summary": "Fonction\u0020qui\u0020cr\u00E9e\u0020les\u0020fiches\u0020de\u0020frais\u0020\u0028via\u0020des\u0020INSERT\u0020SQL\u0029",
            "url": "namespaces/default.html#function_creationFichesFrais"
        },                {
            "fqsen": "\\creationFraisForfait\u0028\u0029",
            "name": "creationFraisForfait",
            "summary": "Fonction\u0020qui\u0020cr\u00E9e\u0020des\u0020lignes\u0020de\u0020frais\u0020au\u0020forfait\u0020\u0028via\u0020des\u0020INSERT\u0020SQL\u0029",
            "url": "namespaces/default.html#function_creationFraisForfait"
        },                {
            "fqsen": "\\getDesFraisHorsForfait\u0028\u0029",
            "name": "getDesFraisHorsForfait",
            "summary": "Fonction\u0020qui\u0020retourne\u0020des\u0020exmples\u0020de\u0020frais\u0020hors\u0020forfait\u0020pour\u0020de\u0020la\u0020g\u00E9n\u00E9ration\nal\u00E9atoire",
            "url": "namespaces/default.html#function_getDesFraisHorsForfait"
        },                {
            "fqsen": "\\updateMdpVisiteur\u0028\u0029",
            "name": "updateMdpVisiteur",
            "summary": "Fonction\u0020qui\u0020met\u0020\u00E0\u0020jour\u0020les\u0020mots\u0020de\u0020passe\u0020des\u0020visisteurs\u0020avec\u0020des\u0020mots\u0020de\npass\u0020al\u00E9atoire",
            "url": "namespaces/default.html#function_updateMdpVisiteur"
        },                {
            "fqsen": "\\creationFraisHorsForfait\u0028\u0029",
            "name": "creationFraisHorsForfait",
            "summary": "Fonction\u0020qui\u0020cr\u00E9e\u0020des\u0020lignes\u0020de\u0020frais\u0020hors\u0020forfait\u0020\u0028via\u0020des\u0020INSERT\u0020SQL\u0029",
            "url": "namespaces/default.html#function_creationFraisHorsForfait"
        },                {
            "fqsen": "\\majFicheFrais\u0028\u0029",
            "name": "majFicheFrais",
            "summary": "Fonction\u0020qui\u0020met\u0020\u00E0\u0020jour\u0020les\u0020montants\u0020des\u0020fiches\u0020de\u0020frais\u0020\u0028via\u0020des\u0020UPDATE\u0020SQL\u0029",
            "url": "namespaces/default.html#function_majFicheFrais"
        },                {
            "fqsen": "\\getLesComptables\u0028\u0029",
            "name": "getLesComptables",
            "summary": "",
            "url": "namespaces/default.html#function_getLesComptables"
        },                {
            "fqsen": "\\PdoGsbTest",
            "name": "PdoGsbTest",
            "summary": "Generated\u0020by\u0020PHPUnit_SkeletonGenerator\u0020on\u00202017\u002D10\u002D10\u0020at\u002022\u003A10\u003A25.",
            "url": "classes/PdoGsbTest.html"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "Sets\u0020up\u0020the\u0020fixture,\u0020for\u0020example,\u0020opens\u0020a\u0020network\u0020connection.",
            "url": "classes/PdoGsbTest.html#method_setUp"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtearDown\u0028\u0029",
            "name": "tearDown",
            "summary": "Tears\u0020down\u0020the\u0020fixture,\u0020for\u0020example,\u0020closes\u0020a\u0020network\u0020connection.",
            "url": "classes/PdoGsbTest.html#method_tearDown"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003Atest__destruct\u0028\u0029",
            "name": "test__destruct",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_test__destruct"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestGetPdoGsb\u0028\u0029",
            "name": "testGetPdoGsb",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testGetPdoGsb"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestGetInfosVisiteur\u0028\u0029",
            "name": "testGetInfosVisiteur",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testGetInfosVisiteur"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestGetLesFraisHorsForfait\u0028\u0029",
            "name": "testGetLesFraisHorsForfait",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testGetLesFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestGetNbjustificatifs\u0028\u0029",
            "name": "testGetNbjustificatifs",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testGetNbjustificatifs"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestGetLesFraisForfait\u0028\u0029",
            "name": "testGetLesFraisForfait",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testGetLesFraisForfait"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestGetLesIdFrais\u0028\u0029",
            "name": "testGetLesIdFrais",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testGetLesIdFrais"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestMajFraisForfait\u0028\u0029",
            "name": "testMajFraisForfait",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testMajFraisForfait"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestMajNbJustificatifs\u0028\u0029",
            "name": "testMajNbJustificatifs",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testMajNbJustificatifs"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestEstPremierFraisMois\u0028\u0029",
            "name": "testEstPremierFraisMois",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testEstPremierFraisMois"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestDernierMoisSaisi\u0028\u0029",
            "name": "testDernierMoisSaisi",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testDernierMoisSaisi"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestCreeNouvellesLignesFrais\u0028\u0029",
            "name": "testCreeNouvellesLignesFrais",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testCreeNouvellesLignesFrais"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestCreeNouveauFraisHorsForfait\u0028\u0029",
            "name": "testCreeNouveauFraisHorsForfait",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testCreeNouveauFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestSupprimerFraisHorsForfait\u0028\u0029",
            "name": "testSupprimerFraisHorsForfait",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testSupprimerFraisHorsForfait"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestGetLesMoisDisponibles\u0028\u0029",
            "name": "testGetLesMoisDisponibles",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testGetLesMoisDisponibles"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestGetLesInfosFicheFrais\u0028\u0029",
            "name": "testGetLesInfosFicheFrais",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testGetLesInfosFicheFrais"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003AtestMajEtatFicheFrais\u0028\u0029",
            "name": "testMajEtatFicheFrais",
            "summary": "",
            "url": "classes/PdoGsbTest.html#method_testMajEtatFicheFrais"
        },                {
            "fqsen": "\\PdoGsbTest\u003A\u003A\u0024object",
            "name": "object",
            "summary": "",
            "url": "classes/PdoGsbTest.html#property_object"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
